In [8]:
import pandas as pd
import json

In [15]:
tweetList = []

In [16]:
with open('google.json') as json_file:  
    data = json.load(json_file)
   
    for item in data :
        hashtags = ''
        for hashtag in item['entities']['hashtags']:
            hashtags += hashtag['text'] + ' ';
        theTweet = item['text']
        if('extended_tweet' in item.keys()) :
            theTweet = item['extended_tweet']['full_text']
        tweetList.append([item['id'], 
                          item['created_at'], 
                          theTweet,
                          item['user']['id'],
                          item['user']['name'],
                          item['user']['screen_name'],
                          hashtags,
                          item['source']])
        
dfStream = pd.DataFrame(tweetList, columns=['id','createdDate',
                                            'text','userId',
                                            'userName','userAccount',
                                            'hashtags','source'])
dfStream

,id,createdDate,text,userId,userName,userAccount,hashtags,source
0,1115519344405098496,Tue Apr 09 07:38:31 +0000 2019,RT @AMI895_AMI: All are equal. #WomeninTech #w...,943917032,Eva Prokop,EvaProkop,WomeninTech womenpower,"<a href=""https://ifttt.com"" rel=""nofollow"">IFT..."
1,1115519346338598912,Tue Apr 09 07:38:32 +0000 2019,RT @candouragency: üéôÔ∏è Episode 4 of Search with...,409658166,Eoghan Quigley,IsEoghan,,"<a href=""http://twitter.com/download/android"" ..."
2,1115519348959920128,Tue Apr 09 07:38:32 +0000 2019,RT @RenwaX23: Xiaomi Mi Browser + Mint Browser...,147175291,Pethuraj M,Pethuraj,0day,"<a href=""http://twitter.com/download/iphone"" r..."
3,1115519352718204933,Tue Apr 09 07:38:33 +0000 2019,Read former @humanities_chi @chiuni @yourUCSU ...,1011245933911314432,Dr Rachel Crossland,DrRCrossland,,"<a href=""http://twitter.com/download/iphone"" r..."
4,1115519354399903744,Tue Apr 09 07:38:34 +0000 2019,@AlgateBronwen @BackupRequired @Abdulaziz_Ada ...,1050159820018307072,Melody McIntyre,MelodyM05174377,,"<a href=""http://twitter.com"" rel=""nofollow"">Tw..."
5,1115519354752458752,Tue Apr 09 07:38:34 +0000 2019,RT @tonyblackburn: Today is the day that Googl...,1559922691,Pauline Brawn,Rugbydoris,,"<a href=""http://twitter.com/#!/download/ipad"" ..."
6,1115519360255184896,Tue Apr 09 07:38:35 +0000 2019,@manicode Have you seen https://t.co/5lc4fx7jv5,411311210,Mitchell Harper,HarperMitchell,,"<a href=""http://twitter.com/download/android"" ..."
7,1115519361421279233,Tue Apr 09 07:38:35 +0000 2019,google at xxxl porno klips comics sex gallery ...,694866385328017409,Cammodel 18+,MistrRaiz_22,,"<a href=""http://twitter.com"" rel=""nofollow"">Tw..."
8,1115519363602370560,Tue Apr 09 07:38:36 +0000 2019,"If this tracklist is the full tracklist, this ...",950269792715341824,üíú Laureldo Books,maoxianjia94,,"<a href=""http://twitter.com/download/iphone"" r..."
9,1115519363795357697,Tue Apr 09 07:38:36 +0000 2019,I would have voted @UKLabour but won‚Äôt be as I...,219768443,Jen üá™üá∫,Soos_elle,,"<a href=""http://twitter.com/download/iphone"" r..."

In [18]:
dfStream.loc[7,'text']

'google at xxxl porno klips comics sex gallery girlfriend porn uk nude raider game lisa matthews naked  https://t.co/9njaDaknbd'

In [21]:
tweetList = []
with open('scoopy.json') as json_file:  
    data = json.load(json_file)
    listTweets = data['statuses']
    for item in listTweets :
        hashtags = ''
        for hashtag in item['entities']['hashtags']:
            hashtags += hashtag['text'] + ' ';
        theTweet = item['text']
        if('extended_tweet' in item.keys()) :
            theTweet = item['extended_tweet']['full_text']
        tweetList.append([item['id'], 
                          item['created_at'], 
                          theTweet,
                          item['user']['id'],
                          item['user']['name'],
                          item['user']['screen_name'],
                          hashtags])
dfSearchScoopy = pd.DataFrame(tweetList, columns=['id','createdDate','text',
                                                 'userId','userName','userAccount',
                                                 'hashtags'])
dfSearchScoopy

,id,createdDate,text,userId,userName,userAccount,hashtags
0,1114881615258218497,Sun Apr 07 13:24:25 +0000 2019,@bramsaputraa walaaaah skrng motornya udah bis...,2799713704,mood,rismawy_,
1,1114502188951166976,Sat Apr 06 12:16:42 +0000 2019,@koernaen ini badan bukan scoopy yang di unbox...,435587738,Widya Kridawidyani,wdykrd,
2,1114444233589395456,Sat Apr 06 08:26:25 +0000 2019,RT @gukgukguk_: ‚ú® Cie viral\n\nJanuari : 80jt\...,1165789080,ü•Ä,rhosinante,
3,1114441204672880640,Sat Apr 06 08:14:23 +0000 2019,RT @gukgukguk_: ‚ú® Cie viral\n\nJanuari : 80jt\...,1005807329655156736,sunflawahhüçâ,sproutsqueezy,
4,1114440301542686720,Sat Apr 06 08:10:47 +0000 2019,‚ú® Cie viral\n\nJanuari : 80jt\nFebruari : unbo...,533814110,Heniüå±,gukgukguk_,
5,1113823522726375425,Thu Apr 04 15:19:56 +0000 2019,"males baca peraturan, giliran salah marah2. pa...",40858608,ùìùùì≤ùì∑ùì≠ùîÇùì™,putnindya,
6,1113087281466826752,Tue Apr 02 14:34:22 +0000 2019,@renjhuwn @nctjaernin yaudah mending saya unbo...,841177204163727360,Ï††,nctjyeno,
7,1113016462627622912,Tue Apr 02 09:52:58 +0000 2019,@taegguk @daraprayoga_ Ada motor scoopy yg unb...,995259820251824129,dian maria,dianmaria15,
8,1112723671884267522,Mon Apr 01 14:29:31 +0000 2019,@bacotamatda Aku maunya scoopy. Biar di unboxingüåö,1098857834538663938,fanüêß,popicelatte,

In [22]:
dfSearchScoopy.loc[8, 'userName']

'fanüêß'

In [5]:
tweetList = []
with open('search1.json') as json_file:  
    data = json.load(json_file)
    item = data['statuses'][0]
    hashtags = ''
    for hashtag in item['entities']['hashtags']:
        hashtags += hashtag['text'] + ' ';
    tweetList.append([item['id'], 
                      item['created_at'], 
                      item['text'],
                      item['user']['id'],
                      item['user']['name'],
                      item['user']['screen_name'],
                      hashtags])
dfSearch = pd.DataFrame(tweetList, columns=['id','createdDate','text','userId','userName','userAccount','hashtags'])
dfSearch

,id,createdDate,text,userId,userName,userAccount,hashtags
0,1052218752454995968,Tue Oct 16 15:24:34 +0000 2018,Testing for Data Science Class Purwadhika\n\n#...,335913267,Baron P.Hartono,BaronHartono,databertasbih kucinggans

In [24]:
tweetList = []
with open('cammodel.json') as json_file:  
    data = json.load(json_file)
   
    for item in data :
        hashtags = ''
        for hashtag in item['entities']['hashtags']:
            hashtags += hashtag['text'] + ' ';
        theTweet = item['text']
        if('extended_tweet' in item.keys()) :
            theTweet = item['extended_tweet']['full_text']
        tweetList.append([item['id'], 
                          item['created_at'], 
                          theTweet,
                          item['user']['id'],
                          item['user']['name'],
                          item['user']['screen_name'],
                          hashtags])
        
dfUserTweets = pd.DataFrame(tweetList, columns=['id','createdDate','text',
                                                'userId','userName','userAccount',
                                                'hashtags'])
dfUserTweets

,id,createdDate,text,userId,userName,userAccount,hashtags
0,1115536028637511681,Tue Apr 09 08:44:49 +0000 2019,vidio sapphicerotica models bar rafael naked b...,694866385328017409,Cammodel 18+,MistrRaiz_22,
1,1115535956206075904,Tue Apr 09 08:44:32 +0000 2019,elliot porn freebiggirlporn com fucking hogtie...,694866385328017409,Cammodel 18+,MistrRaiz_22,
2,1115535796700876800,Tue Apr 09 08:43:54 +0000 2019,black dick galleries exotic nude massage video...,694866385328017409,Cammodel 18+,MistrRaiz_22,
3,1115535707186126848,Tue Apr 09 08:43:32 +0000 2019,skirt pussy pics naked guitar player fucking c...,694866385328017409,Cammodel 18+,MistrRaiz_22,
4,1115535574360834050,Tue Apr 09 08:43:01 +0000 2019,clip kashmiri naked women farting porn movies ...,694866385328017409,Cammodel 18+,MistrRaiz_22,
5,1115535470476374017,Tue Apr 09 08:42:36 +0000 2019,girls naked videos teen-mindy italy fat nude g...,694866385328017409,Cammodel 18+,MistrRaiz_22,
6,1115535343875502080,Tue Apr 09 08:42:06 +0000 2019,robot porn videos sarah palin naked videos blo...,694866385328017409,Cammodel 18+,MistrRaiz_22,
7,1115535127638085632,Tue Apr 09 08:41:14 +0000 2019,exgirlfriend blog sex anime movie hot naked se...,694866385328017409,Cammodel 18+,MistrRaiz_22,
8,1115535043949211650,Tue Apr 09 08:40:54 +0000 2019,porn porn quiz games gif bikini strippin g fem...,694866385328017409,Cammodel 18+,MistrRaiz_22,
9,1115534806241173504,Tue Apr 09 08:39:58 +0000 2019,video expo sex island download pornofficegirls...,694866385328017409,Cammodel 18+,MistrRaiz_22,
10,1115534666281439233,Tue Apr 09 08:39:24 +0000 2019,latinas aunty boy sex thick asian topless anal...,694866385328017409,Cammodel 18+,MistrRaiz_22,
11,1115534501353013248,Tue Apr 09 08:38:45 +0000 2019,girls nude pics for phone older black men porn...,694866385328017409,Cammodel 18+,MistrRaiz_22,
12,1115534395039977473,Tue Apr 09 08:38:20 +0000 2019,adults with adhd and relationships mp4 free se...,694866385328017409,Cammodel 18+,MistrRaiz_22,
13,1115534165867421696,Tue Apr 09 08:37:25 +0000 2019,mature fucking galleries next door home girls ...,694866385328017409,Cammodel 18+,MistrRaiz_22,
14,1115534047080591360,Tue Apr 09 08:36:57 +0000 2019,adults african live sex guyanese sex vids hard...,694866385328017409,Cammodel 18+,MistrRaiz_22,
15,1115533958056501248,Tue Apr 09 08:36:35 +0000 2019,movie 2008 noway nudes free interracial porn m...,694866385328017409,Cammodel 18+,MistrRaiz_22,
16,1115533852058050560,Tue Apr 09 08:36:10 +0000 2019,in french angelina jolie naked in tomb raider ...,694866385328017409,Cammodel 18+,MistrRaiz_22,
17,1115533769426001920,Tue Apr 09 08:35:50 +0000 2019,youtube pamela anderson sex sexo oral gratis f...,694866385328017409,Cammodel 18+,MistrRaiz_22,
18,1115533538743463936,Tue Apr 09 08:34:55 +0000 2019,teen fucked slow hot girls on the nudebeach lo...,694866385328017409,Cammodel 18+,MistrRaiz_22,
19,1115533339874689024,Tue Apr 09 08:34:08 +0000 2019,during sex sex with girl in her sleep fuckig g...,694866385328017409,Cammodel 18+,MistrRaiz_22,

In [7]:
tweetList = []
with open('stream1.json') as json_file:  
    data = json.load(json_file)
   
    for item in data :
        hashtags = ''
        for hashtag in item['entities']['hashtags']:
            hashtags += hashtag['text'] + ' ';
        tweetList.append([item['id'], 
                          item['created_at'], 
                          item['text'],
                          item['user']['id'],
                          item['user']['name'],
                          item['user']['screen_name'],
                          hashtags])
        
dfStream1 = pd.DataFrame(tweetList, columns=['id','createdDate','text','userId','userName','userAccount','hashtags'])
dfStream1

,id,createdDate,text,userId,userName,userAccount,hashtags
0,1052449854809624578,Wed Oct 17 06:42:53 +0000 2018,Google will charge Android manufacturers for t...,26001977,Geeky Gadgets,GeekyGadgets,
1,1052449858416726017,Wed Oct 17 06:42:54 +0000 2018,King of dark fantasy. Summon today. App Store:...,14535292,rblprd,rblprd,DarkSummoner
2,1052449860975284227,Wed Oct 17 06:42:55 +0000 2018,RT @richardcalhoun: #Grieve represents the @Be...,14368178,Tom Brook,DrTEB,Grieve Leave
3,1052449862271291394,Wed Oct 17 06:42:55 +0000 2018,RT @oLo5NdA7VTElVBX: Google play - &gt;https:/...,42011312,4everwithUleesunho,nayd_dyan,
4,1052449862741106688,Wed Oct 17 06:42:55 +0000 2018,RT @JillWineBanks: Outrageous attempt to keep ...,289639293,Noam,i_am_noam,
5,1052449864733388801,Wed Oct 17 06:42:55 +0000 2018,King of dark fantasy. Summon today. App Store:...,2845275821,Chunk Eee,chunky5523,DarkSummoner
6,1052449864943054853,Wed Oct 17 06:42:56 +0000 2018,RT @HNIJohnMiller: 20) The James Damore Google...,756119370686984192,mh01701,Marsh01701,
7,1052449865823911938,Wed Oct 17 06:42:56 +0000 2018,Google to Encrypt Android Cloud Backups With Y...,18251249,Scripter,thomas_metz,
8,1052449874199932928,Wed Oct 17 06:42:58 +0000 2018,"Apple, Google, Microsoft, and Mozilla have ann...",983213188811337730,Crazy Movie,crazymoviega,
9,1052449876737445888,Wed Oct 17 06:42:58 +0000 2018,@Gavuza88 These Google guys can eat a üçÜ,975422131,‚Ä¢ umXhosa ‚Ä¢,qPhiwez,

In [8]:
tweetList = []
with open('yoga.json') as json_file:  
    data = json.load(json_file)
   
    for item in data :
        hashtags = ''
        for hashtag in item['entities']['hashtags']:
            hashtags += hashtag['text'] + ' ';
        tweetList.append([item['id'], 
                          item['created_at'], 
                          item['text'],
                          item['user']['id'],
                          item['user']['name'],
                          item['user']['screen_name'],
                          hashtags])
        
dfStream1 = pd.DataFrame(tweetList, columns=['id','createdDate','text','userId','userName','userAccount','hashtags'])
dfStream1

,id,createdDate,text,userId,userName,userAccount,hashtags
0,1052450732069318656,Wed Oct 17 06:46:22 +0000 2018,Scuffles Break Out at Indian Temple Town Over ...,41552379,CityFXbroker üë©üèª‚Äçüíª,iversue,iverIn
1,1052450773219590145,Wed Oct 17 06:46:32 +0000 2018,Trail run with the pooch and yoga. \n*breeeeea...,293440597,J,Adventurooga,
2,1052450781071376385,Wed Oct 17 06:46:34 +0000 2018,@TradesTalk A bit of yoga #TradesTalk,767738190572683266,PlumbMaid,plumbmaid,TradesTalk
3,1052450789770387460,Wed Oct 17 06:46:36 +0000 2018,RT @KripaSh65065519: #UniqueWayToMendYoungMind...,3505933886,Kokila Bhatnagar,KokilaBhatnagar,UniqueWayToMendYoungMinds
4,1052450808665661440,Wed Oct 17 06:46:41 +0000 2018,Good luck @magnetize - looking forward to supp...,18002497,Kate Percy‚Äôs Go Faster Food,gofasterfood,
5,1052450829947625474,Wed Oct 17 06:46:46 +0000 2018,Chilled view of the camp from the line-up üòé\n#...,2390400696,Sion Surf Camp,sionsurflanka,beachfrontsurfcamp onthedoorstep sionsurfcamp ...
6,1052450843830743040,Wed Oct 17 06:46:49 +0000 2018,gangbang my wife greek sex amateur milf cock c...,1051931776896065536,Sarah Bobo,SarahBo69261287,
7,1052450849224560640,Wed Oct 17 06:46:50 +0000 2018,RT @HareKrishna_hkr: Bhakti yoga is aimed at g...,75514149,GoodLord God Krishna,krish4ever,
8,1052450876047220736,Wed Oct 17 06:46:57 +0000 2018,public sex blowjob japanese asian lesbians mak...,3392264247,Elina,evgeniuspetrov,
9,1052450899279454210,Wed Oct 17 06:47:02 +0000 2018,Living the creative life is so much more than ...,253424247,Kathryn Sturges,kathrynsturges,

In [9]:
tweetList = []
with open('teletubies.json') as json_file:  
    data = json.load(json_file)
    listTweets = data['statuses']
    for item in listTweets :
        hashtags = ''
        for hashtag in item['entities']['hashtags']:
            hashtags += hashtag['text'] + ' ';
        tweetList.append([item['id'], 
                          item['created_at'], 
                          item['text'],
                          item['user']['id'],
                          item['user']['name'],
                          item['user']['screen_name'],
                          hashtags])
dfSearchYoung = pd.DataFrame(tweetList, columns=['id','createdDate','text','userId','userName','userAccount','hashtags'])
dfSearchYoung

,id,createdDate,text,userId,userName,userAccount,hashtags
0,1052483236096487424,Wed Oct 17 08:55:32 +0000 2018,teletubies mirip Amri,1052438619540066307,Yoga Megantoro,megantoro_yoga,
1,1052481755238682624,Wed Oct 17 08:49:39 +0000 2018,teletubies usaha dagang siomay,335913267,Baron P.Hartono,BaronHartono,
2,1052481679313358848,Wed Oct 17 08:49:21 +0000 2018,teletubies kasih karunia,335913267,Baron P.Hartono,BaronHartono,
3,1052481558890799104,Wed Oct 17 08:48:52 +0000 2018,teletubies kasihan ya,335913267,Baron P.Hartono,BaronHartono,
4,1052481518239502336,Wed Oct 17 08:48:42 +0000 2018,teletubies kecebur dikali,335913267,Baron P.Hartono,BaronHartono,
5,1052481458160320512,Wed Oct 17 08:48:28 +0000 2018,teletubies murah hati,335913267,Baron P.Hartono,BaronHartono,
6,1052481200302960640,Wed Oct 17 08:47:26 +0000 2018,teletubies merdeka karena hinaan,335913267,Baron P.Hartono,BaronHartono,
7,1052481125061255168,Wed Oct 17 08:47:09 +0000 2018,teletubies tawuran sama akatsuki,335913267,Baron P.Hartono,BaronHartono,
8,1052481038679592960,Wed Oct 17 08:46:48 +0000 2018,teletubies naik haji,335913267,Baron P.Hartono,BaronHartono,
9,1052480977786695680,Wed Oct 17 08:46:33 +0000 2018,teletubies gerhana matahari,335913267,Baron P.Hartono,BaronHartono,
10,1052480885751042048,Wed Oct 17 08:46:11 +0000 2018,teletubies karya maha agung,335913267,Baron P.Hartono,BaronHartono,
11,1052480784852869120,Wed Oct 17 08:45:47 +0000 2018,teletubies dipsi lebih macho dari pada po dan ...,335913267,Baron P.Hartono,BaronHartono,
12,1052460332281675776,Wed Oct 17 07:24:31 +0000 2018,@AKMJSQ Teletubies kebaca .. Telerabies wkwkq,749077459094515713,teh baby una·¥¨·¥∑·¥π·¥∂üêØ,97eunha_gf,
13,1052356240225890304,Wed Oct 17 00:30:54 +0000 2018,Tour Bromo Murah ! Harga mulai 365rb/org l Men...,3005027173,! Wisata Murah,EmdeTravel,
14,1052250223609753605,Tue Oct 16 17:29:37 +0000 2018,"@RifdahPida gapapa pid, mau teletubies jg ndak...",918434893,Nan.,kintankinantii,
15,1052245582008311808,Tue Oct 16 17:11:11 +0000 2018,"@2OsYUJIN Beberapa hari ini liat kamu 5 L , ak...",912612784034082816,Mika !,mikakeey,
16,1052192675271598086,Tue Oct 16 13:40:57 +0000 2018,@miaghani @syahrulcaon @terkimul @usnul Rame r...,145995050,Fachrur,ro_zzy,
17,1052183057569013760,Tue Oct 16 13:02:44 +0000 2018,@jokowi aku kira ini rumah teletubies pak,2368497942,Dnddyn,dnddyn,
18,1052175156842393600,Tue Oct 16 12:31:20 +0000 2018,"@dyt_taufik @shitlicious Memang, masnya wes ng...",1049119101472235521,Girespati,Girespati1,
19,1052173706154262528,Tue Oct 16 12:25:34 +0000 2018,@injuniehw Gubrak wkwkwkwkw\nTerus berakhir de...,177063884,üê∞djüêª,dwijulitiara,
20,1052159945771081728,Tue Oct 16 11:30:53 +0000 2018,Tour Bromo Murah ! Harga mulai 365rb/org l Men...,3005027173,! Wisata Murah,EmdeTravel,
21,1052147350477496321,Tue Oct 16 10:40:50 +0000 2018,RT @bangun_d: @karniilyas Saat dikuasai O'ON (...,942447265020395520,zahra,zahra36490002,
22,1052142281925349376,Tue Oct 16 10:20:42 +0000 2018,"Dulu kalau matahari mulai tenggelam, maka tele...",553345796,Wahyu Chuck'z,wahyu_chuckz,
23,1052135009207767045,Tue Oct 16 09:51:48 +0000 2018,"Maaf bukan apa, tp mustahil ada cowok kek gitu...",2533664161,Yogi,Sygkuu,
24,1052112322418888704,Tue Oct 16 08:21:39 +0000 2018,RT @bangun_d: @karniilyas Saat dikuasai O'ON (...,2710941804,JON‚úåÔ∏è,babeh_jono,
25,1052111808658518016,Tue Oct 16 08:19:37 +0000 2018,@karniilyas Saat dikuasai O'ON (Orang Orang ng...,1035022459047620608,02_Rudy D Bangun,bangun_d,
26,1052087921006665728,Tue Oct 16 06:44:41 +0000 2018,"@defrdaniel enggak, ava yang tadi kaya teletub...",886907045525438464,Ïä¨Ìîà ÏïÑÍ∏∞,wonyhoungi,
27,1052049307069607936,Tue Oct 16 04:11:15 +0000 2018,@soegihpw Teletubies berpelukaan ü§ò,563843517,Ridho Adiyat,odoyyridho,
28,1052043062757580800,Tue Oct 16 03:46:26 +0000 2018,target lepas ni nak bawa wife dan anak pergi D...,1634907650,"yeen takda, yeen tidur.",yeenhamzah,
29,1052022897529610240,Tue Oct 16 02:26:19 +0000 2018,RT @arangga_aria: saat itu gua lihat ada cewe ...,1294288844,Nasyaale,nasya_aleyda49,
...,...,...,...,...,...,...,...
70,1050924003546693633,Sat Oct 13 01:39:42 +0000 2018,"Sering liat , teman ulangtahun diromantisin pa...",537727426,Yessy H,Yessyhernaa,
71,1050881061884973057,Fri Oct 12 22:49:04 +0000 2018,Berpelukaaaaaaaaaannnnnnn~\n.\n.\n.\n#teletubi...,75737934,Oki P Putri,PoetriAL16,teletubies instagram bestfriend like4likes lat...
72,1050831189320167425,Fri Oct 12 19:30:53 +0000 2018,Tour Bromo Murah ! Harga mulai 365rb/org l Men...,3005027173,! Wisata Murah,EmdeTravel,
73,1050798442681782272,Fri Oct 12 17:20:46 +0000 2018,"@yuwonooktav Mbien, pertama kali ditukokno Sak...",324275519,"""BLISABLI"" Febriandhika",blisabli,
74,1050790775829581824,Fri Oct 12 16:50:18 +0000 2018,@SK_HanJisung @SK_Hyeonjin00 GGT? Ganteng-gant...,1032988454454349826,Î¶¨ÎÖ∏ #IamYou.,SK_LeeKnow98,
75,1050790544522145793,Fri Oct 12 16:49:23 +0000 2018,"@333ars hyung teletubies dong berarti --""",2341794026,Defü§ò,jaebeoxm,
76,1050787850323615744,Fri Oct 12 16:38:40 +0000 2018,@SK_Mark99 Iya nih saya need peluk SKZ sekaran...,1032988454454349826,Î¶¨ÎÖ∏ #IamYou.,SK_LeeKnow98,
77,1050784389431324672,Fri Oct 12 16:24:55 +0000 2018,RT @Tommy_Pambudi: jadi kalau kayak gini kampr...,435788805,mull,mulya_ahmad,GameOfThrones
78,1050783331720167424,Fri Oct 12 16:20:43 +0000 2018,jadi kalau kayak gini kampret mau apa? mendaki...,3220567159,GYeqiu,Tommy_Pambudi,GameOfThrones
79,1050778919316598785,Fri Oct 12 16:03:11 +0000 2018,fav cartooooon during my childhood; teletubies...,757711090918694912,sfs,stftmhsbki,
80,1050761116303806464,Fri Oct 12 14:52:26 +0000 2018,@HYJUNHOE97 Teletubies nya mana dong jun?,713085655891357696,Í∞ïÎØºÏïÑ.,HYMINAH97,
81,1050709730262315008,Fri Oct 12 11:28:15 +0000 2018,@wineroses_ Loh mba? Kan blum jelasin kok udh ...,980770042588491777,üåºüåºüåº,SIN6ULARIV,
82,1050672215258103809,Fri Oct 12 08:59:11 +0000 2018,@rlthingy2 Kaya teletubies,2201098592,anxietees,catherineezz,
83,1050654815506771969,Fri Oct 12 07:50:02 +0000 2018,@diaryfromily Ini kenapa dia mirip Po di telet...,977379495534407681,(G)I-DLE üíú,sasejeong,
84,1050642459795972097,Fri Oct 12 07:00:57 +0000 2018,@gidlesyuqi @nctjisuzg Hmm ga ngajak tawur kok...,1293350112,‚òÜ Ji Sung ‚ô†,JiSungGoKongg,
85,1050636963408052224,Fri Oct 12 06:39:06 +0000 2018,@farras_iz Saya ingat teletubies,1156276598,Ashari Ariya,AshariBare,
86,1050629639196966914,Fri Oct 12 06:10:00 +0000 2018,@inkacml @lamunankopi @BudeSumiyati Karena yg ...,718454914964279296,Eryl Hayattul,erylhayattulu,
87,1050611318112182272,Fri Oct 12 04:57:12 +0000 2018,Baru saja mengirim foto @ Bukit Teletubies htt...,543278759,Eklecia Kristin Irmayfri Rona,EklechiaRona,
88,1050599632978374656,Fri Oct 12 04:10:46 +0000 2018,@real_Ioey Berpelukan sla teletubies,808534235103391744,Soojung,GDKRYSTAL94,
89,1050578624020078592,Fri Oct 12 02:47:17 +0000 2018,Ikan teletubies\n\nTingki wingki dipsi lele po...,1027418054185996288,Wawen,wawennnnn,
90,1050551498696876032,Fri Oct 12 00:59:30 +0000 2018,@INYNA07 @jisumgis Pelukan laahhh.. Biat kayak...,814120193504854016,Behell,hellenium25,
91,1050544301698998272,Fri Oct 12 00:30:54 +0000 2018,Tour Bromo Murah ! Harga mulai 365rb/org l Men...,3005027173,! Wisata Murah,EmdeTravel,
92,1050524182763589632,Thu Oct 11 23:10:57 +0000 2018,@sangtravelers Ada lagi padang rumput yg banya...,1043866494998700032,Travel üë£ & Tips ‚úç,asambackpacker1,
93,1050515581546319873,Thu Oct 11 22:36:46 +0000 2018,@exelflores21 @CH_chotimah @RizmaWidiono @P3nj...,1042911958662438912,Efo Hadi üáÆüá©,ibnhusinakib,
94,1050500584762044419,Thu Oct 11 21:37:11 +0000 2018,Berempat kita jadi teletubies.,1886562553,Has Terrible...,hackedbyayt9,
95,1050420980068245504,Thu Oct 11 16:20:52 +0000 2018,@merthamerr Kerjaanya gambling goda sana goda ...,165305043,Baby don't like it,xiaobie96,
96,1050411827627085824,Thu Oct 11 15:44:30 +0000 2018,Urungkan niat lah. Ke taman teletubies aja,92243218,Dwi Febriyanti,febri_219,
97,1050404308888379392,Thu Oct 11 15:14:37 +0000 2018,RT @Next_J2P: @bioedmond Sandiwara maupun tida...,2883487254,Br@volima‚Ñ¢Arie,Next_J2P,
98,1050404272456663040,Thu Oct 11 15:14:28 +0000 2018,@bioedmond Sandiwara maupun tidak.. Ini mirip ...,2883487254,Br@volima‚Ñ¢Arie,Next_J2P,
99,1050391849649631232,Thu Oct 11 14:25:06 +0000 2018,RT @putricandr: permisi paduka @ikramarki disi...,225733157,N√†n√°ng W,nnkadal,

In [10]:
tweetList = []
with open('nlp.json') as json_file:  
    data = json.load(json_file)
    listTweets = data['statuses']
    for item in listTweets :
        hashtags = ''
        for hashtag in item['entities']['hashtags']:
            hashtags += hashtag['text'] + ' ';
        tweetList.append([item['id'], 
                          item['created_at'], 
                          item['text'],
                          item['user']['id'],
                          item['user']['name'],
                          item['user']['screen_name'],
                          hashtags])
dfSearchYoung = pd.DataFrame(tweetList, columns=['id','createdDate','text','userId','userName','userAccount','hashtags'])
dfSearchYoung

,id,createdDate,text,userId,userName,userAccount,hashtags
0,1052484292851318784,Wed Oct 17 08:59:44 +0000 2018,RT @ParallelDots: India among top 15 in artifi...,2409188870,vishram sagar,vishramsagar,ArtificialIntelligence AI Automation
1,1052484221124587520,Wed Oct 17 08:59:27 +0000 2018,RT @BristowColin: Big Data: Planning for Peak ...,934160485993340933,Robin Thomson,RobinTh0mson,
2,1052484173930196992,Wed Oct 17 08:59:15 +0000 2018,RT @BristowColin: Big Data Shaping the Future ...,953289572464635904,Louiza Sokoloff,SokoloffLouiza,
3,1052484153973780486,Wed Oct 17 08:59:11 +0000 2018,RT @murphthesurf: @BellaFlokarti @Pammieoz @Sc...,257028825,Pammieoz,Pammieoz,
4,1052484032905207808,Wed Oct 17 08:58:42 +0000 2018,RT @IainLJBrown: Big Data Shaping the Future o...,969593261479419905,Fedora Rapp,fedora_rapp,
5,1052484010352377856,Wed Oct 17 08:58:36 +0000 2018,@BellaFlokarti @Pammieoz @ScottMorrisonMP Than...,1010831961995108353,murphthesurf,murphthesurf,
6,1052483708417015810,Wed Oct 17 08:57:24 +0000 2018,RT @ParallelDots: The Transformation of Health...,2409188870,vishram sagar,vishramsagar,ArtificialIntelligence AI
7,1052483040721739776,Wed Oct 17 08:54:45 +0000 2018,RT @rtehrani: Cloud Computing and VPN: Busines...,3382138047,The Hippo Shoe,TheHippoShoe,AI machinelearning nlp alexa
8,1052482979769905154,Wed Oct 17 08:54:31 +0000 2018,RT @IainLJBrown: Don't fall for these 3 myths ...,961605272962727936,Nkruma Ignatov,NkrumaIgnatov,MachineLearning ML
9,1052482510511255552,Wed Oct 17 08:52:39 +0000 2018,@SarahRubyWrites NLP apparently,630679523,Cathryn üè≥Ô∏è‚ÄçüåàYes,stickymeringue,

In [12]:
dfSearchYoung.iloc[2]['text']

'RT @BristowColin: Big Data Shaping the Future of Ag Industry on the HAT Wednesday Morning Edition\nRead more here: https://t.co/i1O00N8LkU‚Ä¶'

In [14]:
tweetList = []
with open('yoga1.json') as json_file:  
    data = json.load(json_file)
    listTweets = data['statuses']
    for item in listTweets :
        hashtags = ''
        for hashtag in item['entities']['hashtags']:
            hashtags += hashtag['text'] + ' ';
        tweetList.append([item['id'], 
                          item['created_at'], 
                          item['text'],
                          item['user']['id'],
                          item['user']['name'],
                          item['user']['screen_name'],
                          hashtags])
dfSearchYoung = pd.DataFrame(tweetList, columns=['id','createdDate','text','userId','userName','userAccount','hashtags'])
dfSearchYoung

,id,createdDate,text,userId,userName,userAccount,hashtags
0,1093792163102683137,Fri Feb 08 08:42:28 +0000 2019,We have to stop and be humble enough to unders...,488559778,HOT Yoga Mallorca,HotYogaMallorca,
1,1093792158446960640,Fri Feb 08 08:42:26 +0000 2019,RT @BJP4Rajasthan: #ForTheFirstTime India‚Äôs so...,1056816205120593920,Sonam Kapoor,Sonam___kumar,ForTheFirstTime
2,1093792117539946497,Fri Feb 08 08:42:17 +0000 2019,23‚Ä≥ Yoga half Ball Balance Trainer Fitness Pil...,904953941514784768,motorcyclejacket,motorcyclejack4,
3,1093792079396900864,Fri Feb 08 08:42:08 +0000 2019,RT @KathyChr: I wish university mental health ...,15330022,jenifer daniels üßòüèæ‚Äç‚ôÄÔ∏è,jentrification,
4,1093792026414309376,Fri Feb 08 08:41:55 +0000 2019,RT @ccapturebyme: Yoga beerüç∫üòÑ\n\n#Kangdaniel #...,809269123343478785,nnp29.KD,nannaphat2001,Kangdaniel Í∞ïÎã§ÎãàÏóò
5,1093792022438309888,Fri Feb 08 08:41:54 +0000 2019,RT @CaptRogerVictor: NEW STICKERS ON OUR PILOT...,4725915991,NeeWhaThey,neewhathey,flightattendant Cabincrew airlines avgeek
6,1093792017627389952,Fri Feb 08 08:41:53 +0000 2019,Siamese Jumpsuit https://t.co/hzvjsxj7nU #yoga...,1029955180668887040,ilovebasques.com,ilovebasques,yogapants yoga leggings activewear gym motivat...
7,1093792003803041792,Fri Feb 08 08:41:50 +0000 2019,RT @BJP4Rajasthan: #ForTheFirstTime\n\n‚úì Inter...,1056023020375031808,Raj Sharma,RajSharmavk,ForTheFirstTime
8,1093791985402556417,Fri Feb 08 08:41:45 +0000 2019,Rolling into Friday like... https://t.co/pOBmt...,1058804294055575552,Elle_Daniel_Yoga,elle_yoga,yogapose yogatips YOGA yogaflow yogachallenge ...

In [18]:
tweetList = []
with open('purwadhika1.json') as json_file:  
    data = json.load(json_file)
    listTweets = data['statuses']
    for item in listTweets :
        hashtags = ''
        for hashtag in item['entities']['hashtags']:
            hashtags += hashtag['text'] + ' ';
        tweetList.append([item['id'], 
                          item['created_at'], 
                          item['text'],
                          item['user']['id'],
                          item['user']['name'],
                          item['user']['screen_name'],
                          hashtags])
dfPurwadhika = pd.DataFrame(tweetList, columns=['id','createdDate','text','userId','userName','userAccount','hashtags'])
dfPurwadhika

,id,createdDate,text,userId,userName,userAccount,hashtags
0,1093552618733858816,Thu Feb 07 16:50:36 +0000 2019,Dear @kempanrb dan @BKNgoid apakah PNS/ASN yg ...,237283752,Budi 'Beppe' PH,purwadhika,
1,1093192372316323840,Wed Feb 06 16:59:06 +0000 2019,RT @JeniusConnect: Sekarang kamu bisa belajar ...,427510607,Orang Indonesia,WongIndonesiaOK,
2,1093192319262543872,Wed Feb 06 16:58:54 +0000 2019,RT @JeniusConnect: Yang ditunggu-tunggu akhirn...,427510607,Orang Indonesia,WongIndonesiaOK,
3,1093133921275981824,Wed Feb 06 13:06:50 +0000 2019,RT @JeniusConnect: Yang ditunggu-tunggu akhirn...,136520403,Indah RJ.,indahrje,
4,1093133888442880002,Wed Feb 06 13:06:43 +0000 2019,RT @JeniusConnect: Sekarang kamu bisa belajar ...,136520403,Indah RJ.,indahrje,
5,1093133859716124674,Wed Feb 06 13:06:36 +0000 2019,RT @JeniusConnect: Buat yang tertarik dengan w...,136520403,Indah RJ.,indahrje,
6,1093132989599379456,Wed Feb 06 13:03:08 +0000 2019,Buat yang tertarik dengan workshop kreatif Jen...,704560477196521475,Jenius Connect,JeniusConnect,
7,1093132985858023424,Wed Feb 06 13:03:07 +0000 2019,Sekarang kamu bisa belajar membuat aplikasi de...,704560477196521475,Jenius Connect,JeniusConnect,
8,1093132972960624645,Wed Feb 06 13:03:04 +0000 2019,Temukan kesempatan untuk bertemu narasumber ya...,704560477196521475,Jenius Connect,JeniusConnect,
9,1093132912638054400,Wed Feb 06 13:02:50 +0000 2019,Yang ditunggu-tunggu akhirnya tiba nih. Kali i...,704560477196521475,Jenius Connect,JeniusConnect,

In [20]:
for tweet in dfPurwadhika['text'] :
    print(tweet)
    print('\n')

Dear @kempanrb dan @BKNgoid apakah PNS/ASN yg share posting seperti ini di akun FBnya tdk menyalahi aturan netralitas?


RT @JeniusConnect: Sekarang kamu bisa belajar membuat aplikasi dengan kerangka React Native, coding dan UI design dengan Jenius Tech Team.‚Ä¶


RT @JeniusConnect: Yang ditunggu-tunggu akhirnya tiba nih. Kali ini Jenius X @Purwadhika_ID berkolaborasi untuk membuat rangkaian acara tal‚Ä¶


RT @JeniusConnect: Yang ditunggu-tunggu akhirnya tiba nih. Kali ini Jenius X @Purwadhika_ID berkolaborasi untuk membuat rangkaian acara tal‚Ä¶


RT @JeniusConnect: Sekarang kamu bisa belajar membuat aplikasi dengan kerangka React Native, coding dan UI design dengan Jenius Tech Team.‚Ä¶


RT @JeniusConnect: Buat yang tertarik dengan workshop kreatif Jenius X @Purwadhika_ID Nantikan informasi terbarunya ya!


Buat yang tertarik dengan workshop kreatif Jenius X @Purwadhika_ID Nantikan informasi terbarunya ya!


Sekarang kamu bisa belajar membuat aplikasi dengan kerangka React Native, coding dan UI design dengan Jenius Tech T‚Ä¶ https://t.co/q1lnH3URtr


Temukan kesempatan untuk bertemu narasumber yang akan berbagi pengalaman dan insight di bidang finansial &amp; teknolog‚Ä¶ https://t.co/epiuUiSDyX


Yang ditunggu-tunggu akhirnya tiba nih. Kali ini Jenius X @Purwadhika_ID berkolaborasi untuk membuat rangkaian acar‚Ä¶ https://t.co/0b8XAMT6F5

In [21]:
tweetList = []
with open('scoopy1.json') as json_file:  
    data = json.load(json_file)
    listTweets = data['statuses']
    for item in listTweets :
        hashtags = ''
        for hashtag in item['entities']['hashtags']:
            hashtags += hashtag['text'] + ' ';
        tweetList.append([item['id'], 
                          item['created_at'], 
                          item['text'],
                          item['user']['id'],
                          item['user']['name'],
                          item['user']['screen_name'],
                          hashtags])
dfPurwadhika = pd.DataFrame(tweetList, columns=['id','createdDate','text','userId','userName','userAccount','hashtags'])
dfPurwadhika

,id,createdDate,text,userId,userName,userAccount,hashtags
0,1093793356801437696,Fri Feb 08 08:47:12 +0000 2019,"Adi Saputra, cowo yg kemaren unboxing Honda Sc...",1048836117506666496,yantiyanti,Yusmayanti11,
1,1093793307627384838,Fri Feb 08 08:47:00 +0000 2019,RT @satriaoo: Teruntuk mbak-mbak yang ada di v...,761418920,akun lama,suwumpa,

In [22]:
for tweet in dfPurwadhika['text'] :
    print(tweet)
    print('\n')

Adi Saputra, cowo yg kemaren unboxing Honda Scoopy, nangis di depan pak polisi....

Drama banget hidup mu Di....‚Ä¶ https://t.co/mKBe4vKAxU


RT @satriaoo: Teruntuk mbak-mbak yang ada di video unboxing scoopy, sabar ya.........

Cara Tuhan nunjukkin sifat pasangan itu emang beda-b‚Ä¶